*** Reading local file: /Users/AmandaTran/airflow/logs/spotifyDag/send_email/2019-10-09T00:00:00+00:00/1.log
[2020-07-08 15:36:59,177] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: spotifyDag.send_email 2019-10-09T00:00:00+00:00 [queued]>
[2020-07-08 15:36:59,195] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: spotifyDag.send_email 2019-10-09T00:00:00+00:00 [queued]>
[2020-07-08 15:36:59,195] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-08 15:36:59,195] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-07-08 15:36:59,195] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-08 15:36:59,207] {taskinstance.py:900} INFO - Executing <Task(EmailOperator): send_email> on 2019-10-09T00:00:00+00:00
[2020-07-08 15:36:59,210] {standard_task_runner.py:53} INFO - Started process 31769 to run task
[2020-07-08 15:36:59,292] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: spotifyDag.send_email 2019-10-09T00:00:00+00:00 [running]> Amandas-MacBook-Air-5.local
[2020-07-08 15:36:59,328] {logging_mixin.py:112} INFO - [2020-07-08 15:36:59,328] {configuration.py:320} WARNING - section/key [smtp/smtp_user] not found in config
[2020-07-08 15:36:59,330] {taskinstance.py:1145} ERROR - [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/operators/email_operator.py", line 78, in execute
    mime_subtype=self.mime_subtype, mime_charset=self.mime_charset)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/utils/email.py", line 60, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/utils/email.py", line 106, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airflow/utils/email.py", line 126, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2020-07-08 15:36:59,352] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=spotifyDag, task_id=send_email, execution_date=20191009T000000, start_date=20200708T223659, end_date=20200708T223659
[2020-07-08 15:37:09,151] {logging_mixin.py:112} INFO - [2020-07-08 15:37:09,150] {local_task_job.py:103} INFO - Task exited with return code 1

